name: mobx
version: 1.0.2+2
description: "MobX is a library for reactively managing the state of your applications. Use the power of observables, actions, and reactions to supercharge your Dart and Flutter apps."

homepage: https://github.com/mobxjs/mobx.dart

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  # flutter_test uses 1.1.6, so we cannot use 1.1.7 yet
  meta: ^1.1.6

dev_dependencies:
  fake_async: ^1.0.1
  mockito: ^4.1.1
  test: ^1.9.4
  test_coverage: ^0.4.1
