name: mobx
version: 0.3.6-alpha
description: "MobX is a library for reactively managing the state of your applications. Use the power of observables, actions, and reactions to supercharge your Dart and Flutter apps."
authors:
  - Pavan Podila <pavan@pixelingene.com>
  - Joni Katajam√§ki <joni.katajamaki@gmail.com>
  - Remi Rousselet <darky12s@gmail.com>

homepage: https://github.com/mobxjs/mobx.dart

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  # flutter_test uses 1.1.6, so we cannot use 1.1.7 yet
  meta: ^1.1.6

dev_dependencies:
  test: ^1.6.3
  fake_async: ^1.0.1
  mockito: ^4.0.0
  test_coverage: ^0.3.0
