name: mobx
version: 0.0.37
description: "MobX is a library for reactively managing the state of your applications. Use the power of observables, actions, and reactions
to supercharge your Dart and Flutter apps."
author: Pavan Podila <pavan@pixelingene.com>
homepage: https://github.com/mobxjs/mobx.dart

environment:
  sdk: '>=2.1.0-dev <3.0.0'

dependencies:
  # Flutter uses 1.1.6, so we cannot use 1.1.7 yet
  meta: ^1.1.6

dev_dependencies:
  test: ^1.5.1
  fake_async: ^1.0.1
  mockito: ^4.0.0
  test_coverage: ^0.2.0
