name: mobx
version: 2.6.0
description: "MobX is a library for reactively managing the state of your applications. Use the power of observables, actions, and reactions to supercharge your Dart and Flutter apps."

repository: https://github.com/mobxjs/mobx.dart
issue_tracker: https://github.com/mobxjs/mobx.dart/issues
homepage: https://mobx.netlify.app
topics:
  - reactive-programming
  - state-management
environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  meta: ^1.3.0
  collection: ^1.15.0

dev_dependencies:
  build_runner: ^2.4.9
  coverage: ^1.8.0
  fake_async: ^1.2.0
  lints: ^5.0.0
  mocktail: ^1.0.3
  test: ^1.17.0
