name: mobx
version: 2.0.7+5
description: "MobX is a library for reactively managing the state of your applications. Use the power of observables, actions, and reactions to supercharge your Dart and Flutter apps."

homepage: https://github.com/mobxjs/mobx.dart

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  meta: ^1.3.0

dev_dependencies:
  build_runner: ^2.0.6
  collection: ^1.15.0
  coverage: ^1.0.1
  fake_async: ^1.2.0
  lints: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.17.0
