name: mobx_examples
description: A set of examples showing effective use of MobX.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  connectivity:
  cupertino_icons: ^1.0.2
  dart_json_mapper: ^2.0.5
  dart_json_mapper_mobx: ^2.0.0
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.0-nullsafety.0
#  github: ^8.0.1
#  hnpwa_client: ^2.0.0
  mobx: ^2.0.0-nullsafety.0
  mobx_codegen: ^2.0.0-nullsafety.0
  provider: ^5.0.0
  shared_preferences:
  url_launcher:
  validators: ^2.0.0

dev_dependencies:
  build_runner: ^1.12.2
  flutter_test:
    sdk: flutter

dependency_overrides:
  flutter_mobx:
    path: ../flutter_mobx
  mobx:
    path: ../mobx
  mobx_codegen:
    path: ../mobx_codegen

flutter:
  uses-material-design: true
  assets:
    - images/
