name: mobx_codegen
description: Code generator for MobX that adds support for annotating your code with @observable, @computed, @action and also creating Store classes. Stores can be created with a mixin or @store.
version: 0.3.6
authors:
  - Joni Katajam√§ki <joni.katajamaki@gmail.com>
  - Pavan Podila <pavan@pixelingene.com>
  - Remi Rousselet <darky12s@gmail.com>
  - Scott Hyndman <scotty.hyndman@gmail.com>

homepage: https://github.com/mobxjs/mobx.dart

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  path: ^1.6.2
  source_gen: ^0.9.4
  mobx: ^0.3.6
  build: ^1.1.4
  analyzer: ^0.36.3

dev_dependencies:
  logging: ^0.11.3
  build_runner: ^1.4.0
  build_test: ^0.10.8
  test_coverage: ^0.3.0
  test: ^1.6.3
  mockito: ^4.0.0
