name: mobx_codegen
description: Code generator for MobX that adds support for annotating your code with @observable, @computed, @action and also creating Store classes.
version: 2.0.1+2

homepage: https://github.com/mobxjs/mobx.dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ^1.2.0
  build: ^2.0.0
  build_resolvers: ^2.0.0
  meta: ^1.3.0
  mobx: ^2.0.1
  path: ^1.8.0
  source_gen: ^1.0.0

dev_dependencies:
  build_runner: ^1.12.2
  build_test: ^2.0.0
  coverage: ^1.0.2
  logging: ^1.0.0
  mocktail: ^0.1.1
  test: ^1.16.8
