name: mobx_codegen
description: Code generator for MobX that adds support for annotating your code with @observable, @computed, @action and also creating Store classes. Stores can be created with a mixin or @store.
version: 0.3.12+1

homepage: https://github.com/mobxjs/mobx.dart

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  analyzer: '>=0.36.3 <0.40.0'
  build: ^1.1.4
  meta: ^1.1.0
  mobx: ^0.4.0
  path: ^1.6.2
  source_gen: ^0.9.4

dev_dependencies:
  build_runner: ^1.7.2
  build_test: ^0.10.9
  logging: ^0.11.3
  mockito: ^4.0.0
  test_coverage: ^0.4.0
  test: ^1.9.4
