name: mobx_codegen
description: Code generator for MobX that adds support for annotating your code with @observable, @computed, @action and also creating Store classes.
version: 1.0.1

homepage: https://github.com/mobxjs/mobx.dart

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  analyzer: ">=0.38.5 <0.40.0"
  build: ^1.1.4
  build_resolvers: ^1.3.2
  meta: ^1.1.0
  mobx: ^1.0.0
  path: ^1.6.2
  source_gen: ^0.9.4

dev_dependencies:
  build_runner: ^1.7.2
  build_test: ^0.10.9
  logging: ^0.11.3
  mockito: ^4.0.0
  test: ^1.9.4
  test_coverage: ^0.4.1
