name: mobx_codegen
description: Code generator for MobX that adds support for annotating your code with @observable, @computed, @action and also creating Store classes.
version: 2.7.5

repository: https://github.com/mobxjs/mobx.dart
issue_tracker: https://github.com/mobxjs/mobx.dart/issues
homepage: https://mobx.netlify.app
topics:
  - reactive-programming
  - state-management
  - codegen

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  analyzer: ">=7.4.0 < 9.0.0"
  build: ">=3.0.0 < 5.0.0"
  meta: ^1.3.0
  mobx: ^2.6.0
  path: ^1.8.0
  source_gen: ">=3.0.0 < 5.0.0"

dev_dependencies:
  build_runner: ^2.6.0
  build_test: ^3.3.0
  coverage: ^1.8.0
  lints: ^5.0.0
  logging: ^1.0.2
  mocktail: ^1.0.0
  test: ^1.20.1
  dart_style: ^3.1.0
