name: mobx_codegen
description: Code generator for MobX that adds support for annotating your code with @observable, @computed, @action and also creating Store classes.
version: 0.0.8
author: Joni Katajam√§ki <joni.katajamaki@gmail.com>
homepage: https://github.com/mobxjs/mobx.dart

environment:
  sdk: '>=2.1.0-dev <3.0.0'

dependencies:
  path: ^1.4.1
  source_gen: ^0.9.4
  mobx: ^0.0.35
  build: ^1.1.0
  analyzer: ^0.35.0

dev_dependencies:
  logging: ^0.11.3
  build_runner: ^1.2.5
  build_test: ^0.10.5
  test_coverage: ^0.2.0
  test: ^1.0.0
  mockito: ^4.0.0
