name: mobx_codegen
description: Code generator for MobX that adds support for annotating your code with @observable, @computed, @action and also creating Store classes.
version: 2.0.7+1

homepage: https://github.com/mobxjs/mobx.dart

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  analyzer: ">=2.8.0 <5.0.0"
  build: ^2.2.1
  build_resolvers: ^2.0.6
  meta: ^1.3.0
  mobx: ^2.0.7
  path: ^1.8.0
  source_gen: ^1.2.1

dev_dependencies:
  build_runner: ^2.1.7
  build_test: ^2.1.5
  coverage: ^1.0.4
  lints: ^2.0.0
  logging: ^1.0.2
  mocktail: ^0.3.0
  test: ^1.20.1

