name: flutter_mobx
description:
  Flutter integration for MobX. It provides the Observer widget that automatically rebuilds
  when the tracked observables change.
version: 0.2.0
author: Joni Katajam√§ki <joni.katajamaki@gmail.com>
homepage: https://github.com/mobxjs/mobx.dart

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  mobx: ^0.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
