name: flutter_mobx
description:
  Flutter integration for MobX. It provides a set of Observer widgets that automatically rebuild
  when the tracked observables change.
version: 2.0.3+1

homepage: https://github.com/mobxjs/mobx.dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.0.0

dev_dependencies:
  build_runner: ^2.0.6
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
