name: flutter_mobx
description:
  Flutter integration for MobX. It provides a set of Observer widgets that automatically rebuild
  when the tracked observables change.
version: 2.3.0

repository: https://github.com/mobxjs/mobx.dart
issue_tracker: https://github.com/mobxjs/mobx.dart/issues
homepage: https://mobx.netlify.app
topics:
  - reactive-programming
  - state-management
  - user-interface

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.6.0
  provider: ^6.0.0

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
