name: flutter_mobx
description:
  Flutter integration for MobX. It provides a set of Observer widgets that automatically rebuild
  when the tracked observables change.
version: 2.0.0-nullsafety.0

homepage: https://github.com/mobxjs/mobx.dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.0.0-nullsafety.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
