name: mobx_codegen_example
description: A starting point for Dart libraries or applications.
version: 0.0.1
author: Joni Katajam√§ki <joni.katajamaki@gmail.com>

environment:
  sdk: '>=2.1.0-dev <3.0.0'

dependencies:
  mobx: ^0.1.0
  mobx_codegen: ^0.1.0

dev_dependencies:
  build_runner: 1.2.6
  test_coverage: ^0.2.0
  test: ^1.0.0

dependency_overrides:
  mobx_codegen:
    path: ../
