name: mobx_codegen_example
description: A starting point for Dart libraries or applications.
version: 0.0.1
author: Joni Katajam√§ki <joni.katajamaki@gmail.com>

environment:
  sdk: '>=2.1.0-dev <3.0.0'

dependencies:
  mobx: ^0.0.35
  mobx_codegen: ^0.0.5

dependency_overrides:
  mobx:
    path: ../../mobx
  mobx_codegen:
    path: ../../mobx_codegen

dev_dependencies:
  build_runner: ^1.2.5
  test_coverage: ^0.2.0
  test: ^1.0.0
