name: Build

on: [push, pull_request]

jobs:
  build_dart_packages:
    runs-on: ubuntu-latest

    container:
      image: dart:${{ matrix.version }}

    strategy:
      matrix:
        package: ["mobx_codegen", "mobx"]
        version: ["stable"]

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: ${{ matrix.package }}
        run: dart pub get

      - name: Analyze
        working-directory: ${{ matrix.package }}
        run: dart analyze --fatal-warnings --fatal-infos .

      - name: Run tests
        working-directory: ${{ matrix.package }}
        run: ../tool/coverage.sh

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: ${{ matrix.package }}
          files: ./${{ matrix.package }}/coverage/lcov.txt

  build_flutter_packages:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package: ["flutter_mobx"]
        channel: ["stable", "beta"]

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ matrix.channel }}

      - name: Install dependencies
        run: flutter packages get
        working-directory: ${{ matrix.package }}

      - name: Analyze
        run: flutter analyze
        working-directory: ${{ matrix.package }}

      - name: Run tests
        run: flutter test --coverage --coverage-path coverage/lcov.txt
        working-directory: ${{ matrix.package }}

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: ${{ matrix.package }}
          files: ./${{ matrix.package }}/coverage/lcov.txt

  build_lint_packages:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: ["stable"]

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ matrix.channel }}

      - name: Install dependencies
        working-directory: mobx_lint
        run: dart pub get

      - name: Analyze
        working-directory: mobx_lint
        run: dart analyze --fatal-warnings --fatal-infos .

      - name: Run tests
        working-directory: mobx_lint_flutter_test
        run: |
          flutter pub get
          flutter test test

